name: deliverance_church_utawala
description: A church App, that helps in streaming sermon.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.27
  mpesa_flutter_plugin: ^1.0.0
  line_icons: ^0.2.0



  http: ^0.12.0+2
  youtube_player_flutter: ^6.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/logos/

  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf

   - family: OpenSans
     fonts:
       - asset: assets/fonts/OpenSans.ttf
